c_compiler: clang
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: clangxx
extend_keys:
- pin_run_as_build
- extend_keys
- ignore_version
- ignore_build_only_deps
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
lua: '5'
numpy: '1.11'
perl: 5.26.0
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '3.8'
r_base: '3.5'
target_platform: osx-64
